"""
Differences from src/search_differential_trail.py:
  - The (start_step, end_step, message_bound, message_differential, op0..op9)
    configuration is generated by config_gen for the target round, not hardcoded.
  - The two 37-step-specific hardcoded Hamming-weight bounds in assign_value
    (W22+W23 = 4 and the six-word = 35) are REMOVED.
  - obj_value ranges are clamped so small end_step values do not crash, with a
    Hamming-weight fallback when the uncontrolled Boolean window is empty.
  - Each stp call is wrapped with a per-call timeout; per-iteration solve times
    are logged, and the final condition count / HE / HW are recorded.
  - Given a round + LC json, it tries local-collision candidates (largest span
    first, since span <= 8 leaves no room for the state collision) until one
    yields a satisfiable DC.

op9 (value transitions) is kept off, faithful to the validated 37-step config.
(Note: src/unit_function_256.py:sha2_value has a variable-naming bug for the A
registers, so enabling op9 would need that fixed first.)
"""

import sys
import os
import subprocess
import time
import json

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "src"))

from unit_function_256 import (sha_e, sha_a, message_expand, sha2_value,  # noqa: E402
                               message_expand_value, read_differential_characteristic)
from config_gen import gen_config, with_value_transitions  # noqa: E402

RESULTS_DC = os.path.join(HERE, "results_dc")
WORK = os.path.join(RESULTS_DC, "_work")
BLOCK = 32
# Use all cores by default; override with SHA2_THREADS=N. (No artificial cap.)
THREADS = os.environ.get("SHA2_THREADS", str(os.cpu_count() or 4))


class DCModel:
    def __init__(self, cfg):
        self.cfg = cfg
        self.start = cfg["start_step"]
        self.end = cfg["end_step"]
        self.mb = cfg["message_bound"]
        self.msgdiff = cfg["message_differential"]
        self.op = [cfg["op%d" % k] for k in range(10)]
        self.declare = []
        self.constraints = []

    def check_assign(self, s):
        if s not in self.declare:
            self.declare.append(s)

    def main(self):
        for i in range(self.start, self.end):
            var_e, con_e = sha_e(BLOCK, self.op[0][i], self.op[1][i], self.op[2][i], i)
            self.constraints.append("".join(con_e))
            for v in var_e:
                self.check_assign(v)
            var_a, con_a = sha_a(BLOCK, self.op[3][i], self.op[4][i], self.op[5][i], i)
            self.constraints.append("".join(con_a))
            for v in var_a:
                self.check_assign(v)
            # op9: value-transition model (sha2_value + derive_cond, real K_i),
            # plus message_expand_value for expanded words. This is the O5-stage
            # validity model in the 2026 procedure; mirrors src/search_differential_trail.py.
            if self.op[9][i]:
                var_v, con_v = sha2_value(BLOCK, "IF", "MAJ", i)
                self.constraints.append("".join(con_v))
                for v in var_v:
                    self.check_assign(v)
                if i > 15:
                    var_mv, con_mv = message_expand_value(BLOCK, i)
                    self.constraints.append("".join(con_mv))
                    for v in var_mv:
                        self.check_assign(v)
        for i in range(self.mb):
            if i > 15:
                var_w, con_w = message_expand(BLOCK, self.op[6][i], self.op[7][i], self.op[8][i], i)
                self.constraints.append("".join(con_w))
                for v in var_w:
                    self.check_assign(v)

    def build(self):
        """Populate self.declare / self.constraints; return (variable_str, constrain_str)."""
        self.declare = []
        self.constraints = []
        self.main()
        self.assign_value()
        return "".join(self.declare), "".join(self.constraints)

    def declared_set(self):
        return set(line.split(":")[0].strip() for line in self.declare)

    def _declared_message_words(self):
        # Only message words actually declared by sha_e/message_expand exist as STP
        # symbols; zeroing an undeclared word triggers "Unresolved symbol".
        declared = set()
        for line in self.declare:
            if line.startswith("wv_"):
                declared.add(int(line.split("_")[1]))
        return declared

    def assign_value(self):
        declared_w = self._declared_message_words()
        # zero the difference of every DECLARED message word NOT in the local collision
        for i in range(self.mb):
            if i in declared_w and i not in self.msgdiff:
                for j in range(BLOCK):
                    self.constraints.append(
                        "ASSERT wv_%d_%d = 0bin0;\nASSERT wd_%d_%d = 0bin0;\n" % (i, j, i, j))
        # require at least one active difference bit among the local-collision words
        terms = []
        for idx in self.msgdiff:
            for j in range(BLOCK):
                terms.append("0bin000000000@wd_%d_%d" % (idx, j))
        self.constraints.append("ASSERT BVGE(BVPLUS(10," + ",".join(terms) + "), 0bin0000000001);\n")
        # zero the state difference before the local collision
        for step in range(self.start - 4, self.start):
            for i in range(BLOCK):
                self.constraints.append(
                    "ASSERT xv_%d_%d = 0bin0;\nASSERT xd_%d_%d = 0bin0;\n"
                    "ASSERT yv_%d_%d = 0bin0;\nASSERT yd_%d_%d = 0bin0;\n" % (
                        step, i, step, i, step, i, step, i))
        # zero A in the collision tail (last 8 state steps) and E (last 4)
        for step in range(self.end - 8, self.end):
            for i in range(BLOCK):
                self.constraints.append("ASSERT xv_%d_%d = 0bin0;\nASSERT xd_%d_%d = 0bin0;\n" % (step, i, step, i))
        for step in range(self.end - 4, self.end):
            for i in range(BLOCK):
                self.constraints.append("ASSERT yv_%d_%d = 0bin0;\nASSERT yd_%d_%d = 0bin0;\n" % (step, i, step, i))
        # NOTE: the 37-step-specific Hamming-weight bounds are intentionally omitted.

    # ---- staged objective TERM builders (each returns a list of 1-bit var names) ----
    # Terms are filtered against the declared set so the objective never references
    # an undeclared symbol (which STP rejects). This also makes O4/O5 sum over
    # exactly the modelled trail.
    def _O1_terms(self, declared):
        """O1: Hamming weight of the highest-index active message word(s)
        (the paper's H(dW22)+H(dW23)). Two highest if >=2 active words, else one."""
        active = sorted(self.msgdiff)
        last = active[-2:] if len(active) >= 2 else active
        return [t for i in last for t in self._wd(i, declared)]

    def _O2_terms(self, declared):
        """O2: total Hamming weight of all message-word differences."""
        return [t for i in sorted(self.msgdiff) for t in self._wd(i, declared)]

    def _O3_terms(self, declared):
        """O3: uncontrolled differential conditions on E16.. = Boolean bit
        conditions (Sigma1 XOR + IF, with variable-specific (t1,t2) counters) over
        [17,end) + Hamming weight H(dE) over [16,end-4). This is the attack's
        differential-condition count (= the differential-probability exponent)."""
        terms = []
        for i in range(17, self.end):
            if self.op[0][i] == 1:
                terms += self._named("ned_xor", i, declared)
            if self.op[1][i] in (1, 4):
                terms += self._named("nev_if", i, declared)
                terms += self._named("ned_if", i, declared)
            elif self.op[1][i] in (2, 3, 5):
                terms += self._named("ned_if", i, declared)
        for i in range(16, self.end - 4):
            terms += self._yd(i, declared)
        return terms

    def _O4_terms(self, declared):
        """O4: total Hamming weight of the A-register differences over the trail."""
        return [t for i in range(self.mb) for t in self._xd(i, declared)]

    def _O5_terms(self, declared):
        """O5: total Hamming weight of the E-register differences over the trail."""
        return [t for i in range(self.mb) for t in self._yd(i, declared)]

    @staticmethod
    def _term(var):
        return "0bin000000000@%s" % var  # pad a 1-bit var to 10 bits for BVPLUS(10)

    def _wd(self, i, declared):
        return [self._term("wd_%d_%d" % (i, j)) for j in range(BLOCK)
                if "wd_%d_%d" % (i, j) in declared]

    def _yd(self, i, declared):
        return [self._term("yd_%d_%d" % (i, j)) for j in range(BLOCK)
                if "yd_%d_%d" % (i, j) in declared]

    def _xd(self, i, declared):
        return [self._term("xd_%d_%d" % (i, j)) for j in range(BLOCK)
                if "xd_%d_%d" % (i, j) in declared]

    def _named(self, prefix, i, declared):
        return [self._term("%s_%d_%d" % (prefix, i, j)) for j in range(BLOCK)
                if "%s_%d_%d" % (prefix, i, j) in declared]


def count_hamming(out_file, message_bound):
    """Count active difference bits (v,d != 0,0) for E (y), W (w), A (x)."""
    data = open(out_file).read().split("\n")
    vv = {"x": {}, "y": {}, "w": {}}
    dd = {"x": {}, "y": {}, "w": {}}
    for line in data:
        if " = " not in line:
            continue
        name = line.replace("ASSERT( ", "").split(" = ")[0].strip()
        val = line.split(" = ")[1].replace(" );", "").strip()
        bit = 1 if "1" in val else 0
        for pref in ("xv", "xd", "yv", "yd", "wv", "wd"):
            if name.startswith(pref + "_"):
                reg = pref[0]
                kind = "v" if pref[1] == "v" else "d"
                key = name[len(pref) + 1:]
                (vv if kind == "v" else dd)[reg][key] = bit
    counts = {}
    for reg in ("x", "y", "w"):
        active = 0
        keys = set(vv[reg]) | set(dd[reg])
        for k in keys:
            if vv[reg].get(k, 0) or dd[reg].get(k, 0):
                active += 1
        counts[reg] = active
    return counts["y"], counts["w"], counts["x"]


def build_specs(R, lc_json=None):
    """Assemble local-collision specs to try, best-first, SOLELY from the
    local-collision search output (results_lc/lc_R.json). No presets: every spec
    is a from-scratch LC-search result. The 'best' LC is tried first; the
    'alternates' (also LC-search outputs) are fallbacks if it is infeasible."""
    if lc_json is None:
        lc_json = os.path.join(HERE, "results_lc", "lc_%d.json" % R)
    if not os.path.exists(lc_json):
        raise FileNotFoundError(
            "No local collision for R=%d at %s. Run lc_search.py %d first "
            "(the LC search is the sole, preset-free source of local collisions)."
            % (R, lc_json, R))
    data = json.load(open(lc_json))
    specs = [dict(data["best"], source="lc-search-best")]
    for alt in data.get("alternates", []):
        specs.append(dict(alt, source="lc-search-alt"))
    # de-duplicate on (start, span, active words)
    seen = set()
    uniq = []
    for s in specs:
        key = (s["start_step"], s["span"], tuple(s["active_words"]))
        if key not in seen:
            seen.add(key)
            uniq.append(s)
    # Feasibility ordering (NOT a preset -- all specs are LC-search outputs):
    # the tail-zeroing in assign_value (zero A over [end-8,end)) needs span >= ~9
    # to leave room for the collision's A/E differences, so a span-6 collision is
    # structurally infeasible. Try adequate-span candidates first, then by the
    # Algorithm-1 objective (fewest active words, then fewest cancellation
    # conditions). The LC-search 'best' still leads when it is feasibility-shaped.
    MIN_FEASIBLE_SPAN = 9
    uniq.sort(key=lambda s: (0 if s["span"] >= MIN_FEASIBLE_SPAN else 1,
                             s.get("num_active", len(s["active_words"])),
                             s.get("cond_total", 0),
                             s["span"]))
    return uniq


# =============================================================================
# The O1->O5 lexicographic cascade (the faithful 2026 DC-search mechanism).
# =============================================================================
def _parse_obj(decoded, name):
    for line in decoded.split("\n"):
        if name in line and " = " in line:
            raw = line.split(" = ")[1].replace(" );", "").replace(");", "").strip()
            if raw.startswith("0x"):
                return int(raw[2:], 16)
            if raw.startswith("0b"):
                return int(raw[2:], 2)
            try:
                return int(raw)
            except ValueError:
                return None
    return None


def _obj_def(name, terms, width=10):
    if not terms:
        return None
    return "%s: BITVECTOR(%d);\nASSERT %s = BVPLUS(%d,%s);\n" % (
        name, width, name, width, ",".join(terms))


def _run_stp(cvc, timeout):
    try:
        R = subprocess.check_output(["stp", cvc, "--cryptominisat", "--threads", THREADS],
                                    stderr=subprocess.STDOUT, timeout=timeout)
        return R.decode(), None
    except subprocess.TimeoutExpired:
        return None, "timeout"
    except subprocess.CalledProcessError as e:
        return None, "error:" + e.output.decode()[:150]


def descend_stage(name, terms, variable, base_constr, carried, tag, timeout,
                  query, width=10, budget=None):
    """Minimize objective `name` = sum(terms), subject to base + carried
    constraints, by descending the BVLE bound. Returns
    (min_value, out_file, carry_clause, iters, status)."""
    os.makedirs(WORK, exist_ok=True)
    iters = []
    obj_def = _obj_def(name, terms, width)
    cvc = os.path.join(WORK, "dc_%s_%s.cvc" % (tag, name))

    if obj_def is None:
        # trivial objective (no terms): just confirm feasibility / get a witness
        with open(cvc, "w") as f:
            f.write(variable); f.write(base_constr); f.write(carried); f.write(query)
        t0 = time.time(); decoded, err = _run_stp(cvc, timeout); dt = time.time() - t0
        if err:
            return None, None, "", [{"stage": name, "dt": round(dt, 2), "result": err.split(":")[0].upper()}], err.split(":")[0]
        if decoded.strip() == "Valid.":
            return None, None, "", [{"stage": name, "dt": round(dt, 2), "result": "UNSAT"}], "infeasible"
        out = os.path.join(WORK, "dc_%s_%s.out" % (tag, name))
        open(out, "w").write(decoded)
        return 0, out, "", [{"stage": name, "achieved": 0, "dt": round(dt, 2), "result": "SAT"}], "ok"

    bound = min((1 << width) - 1, len(terms))
    best_v, best_out, status = None, None, "ok"
    t_start = time.time()
    while True:
        if budget is not None and best_out is not None and (time.time() - t_start) > budget:
            iters.append({"stage": name, "result": "BUDGET"}); break
        with open(cvc, "w") as f:
            f.write(variable); f.write(base_constr); f.write(carried); f.write(obj_def)
            f.write("ASSERT BVLE(%s, 0bin%s);\n" % (name, bin(bound)[2:].zfill(width)))
            f.write(query)
        t0 = time.time(); decoded, err = _run_stp(cvc, timeout); dt = time.time() - t0
        if err:
            iters.append({"stage": name, "bound": bound, "dt": round(dt, 2), "result": err.split(":")[0].upper()})
            status = "ok" if best_out is not None else err.split(":")[0]
            break
        if decoded.strip() != "Valid.":  # SAT
            out = os.path.join(WORK, "dc_%s_%s_%d.out" % (tag, name, bound))
            open(out, "w").write(decoded)
            ach = _parse_obj(decoded, name)
            if ach is None:
                ach = bound
            iters.append({"stage": name, "bound": bound, "achieved": ach, "dt": round(dt, 2), "result": "SAT"})
            best_v, best_out = ach, out
            if ach == 0:
                break
            bound = ach - 1
        else:  # UNSAT -> optimum is the last SAT value
            iters.append({"stage": name, "bound": bound, "dt": round(dt, 2), "result": "UNSAT"})
            status = "ok" if best_out is not None else "infeasible"
            break

    carry = ""
    if best_v is not None:
        carry = obj_def + "ASSERT %s = 0bin%s;\n" % (name, bin(best_v)[2:].zfill(width))
    return best_v, best_out, carry, iters, status


def _cascade_result(status, final_out, optima, iters, mb):
    res = {
        "status": status,
        "found": final_out is not None,
        "min_conditions": optima.get("o3"),
        "stage_optima": optima,
        "iters": iters,
        "total_time": round(sum(it.get("dt", 0) for it in iters), 2),
        "out_file": final_out,
        "sat_outs": [final_out] if final_out else [],
    }
    if final_out is not None:
        he, hw, ha = count_hamming(final_out, mb)
        res.update({"HE": he, "HW": hw, "HA": ha})
    return res


def solve_cascade(cfg, tag, timeout=600, o5_value=True, budget=None, stop_after="o5"):
    """The 2026 staged objective, run as a real lexicographic cascade:
        O1 = H of highest-index active W(s)
        O2 = total H(dW)
        O3 = uncontrolled differential conditions on E16.. (Boolean BD + H(dE))
        O4 = total H(dA)
        O5 = total H(dE)
    Each stage is minimized, then fixed (ASSERT obj_k = v_k) before the next.
    O1-O4 run on the difference model; O5 optionally on the value-transition
    model (op9) for validity (the paper runs value transitions at this stage).
    O3's minimum is the reported differential-condition count.

    stop_after: stop the cascade after this stage ('o1'..'o5'). Use stop_after='o3'
    for a cheap O3 scan (skips the slow, cosmetic O4/O5) when selecting the best
    local collision by differential-condition count."""
    query = "\nQUERY FALSE;\nCOUNTEREXAMPLE;"
    diff = DCModel(cfg)
    var_d, con_d = diff.build()
    decl_d = diff.declared_set()

    carried, optima, all_iters, final_out, status = "", {}, [], None, "ok"
    for name, terms in [("o1", diff._O1_terms(decl_d)), ("o2", diff._O2_terms(decl_d)),
                        ("o3", diff._O3_terms(decl_d)), ("o4", diff._O4_terms(decl_d))]:
        v, out, carry, iters, st = descend_stage(name, terms, var_d, con_d, carried,
                                                  tag, timeout, query, budget=budget)
        all_iters += iters
        optima[name] = v
        if out is not None:
            final_out = out
        if st != "ok":
            status = st
            if out is None:  # stage infeasible/timeout with no witness -> stop
                return _cascade_result(status, final_out, optima, all_iters, cfg["message_bound"])
        carried += carry
        if name == stop_after:
            return _cascade_result(status if final_out else "no_solution",
                                   final_out, optima, all_iters, cfg["message_bound"])

    # O5
    if o5_value:
        val = DCModel(with_value_transitions(cfg))
        var5, con5 = val.build()
        o5_terms = val._O5_terms(val.declared_set())
        base_var, base_con = var5, con5
    else:
        o5_terms, base_var, base_con = diff._O5_terms(decl_d), var_d, con_d
    v, out, carry, iters, st = descend_stage("o5", o5_terms, base_var, base_con, carried,
                                             tag, timeout, query, budget=budget)
    all_iters += iters
    if out is not None:
        optima["o5"], final_out = v, out
    elif o5_value:
        # O5 value-model UNSAT/timeout: the DC may be invalid or just too hard
        # for the in-search validity model. Fall back to the difference-model O5
        # so we still emit the characteristic; find_collision is the final arbiter.
        status = "o5_value_" + st
        v2, out2, _, iters2, _ = descend_stage("o5", diff._O5_terms(decl_d), var_d, con_d,
                                               carried, tag + "_diffO5", timeout, query, budget=budget)
        all_iters += iters2
        if out2 is not None:
            optima["o5"], final_out = v2, out2
    if st != "ok" and status == "ok":
        status = "o5_" + st
    if final_out is not None and status == "ok":
        status = "minimized"
    return _cascade_result(status if final_out else "no_solution", final_out, optima, all_iters, cfg["message_bound"])


def _sat_out_files(res, tag):
    """Final-DC .out file(s) for validation, most-minimized first."""
    return [p for p in res.get("sat_outs", []) if p and os.path.exists(p)]


def run_specs(R, specs, timeout=300, max_attempts=8, init_pro=97,
              validate=True, oracle_timeout=300, max_validate=1, solve_budget=None,
              o5_value=True):
    """Search specs best-first, running the O1->O5 cascade per candidate. With
    validate=True a DC is accepted only when the SFS finder (find_collision.solve_dc)
    produces a verified colliding pair for it; on invalid_dc (UNSAT) we move to the
    next candidate. If the pair search only times out (the trail may still be valid
    but too hard for the solver to confirm in budget), we keep the DC as a
    best-effort artifact and record the timeout honestly."""
    attempts = []
    chosen = None
    chosen_collision = None
    chosen_out = None
    best_effort = None  # (res, out, coll) for the first found DC, if none verify
    if validate:
        import find_collision  # lazy: pulls in verify_collision / parse_dc
    for ci, c in enumerate(specs[:max_attempts]):
        cfg = gen_config(R, c["start_step"], c["start_step"] + c["span"], c["active_words"])
        tag = "R%d_c%d" % (R, ci)
        print("  [R=%d] try %d (%s): start=%d span=%d active=%s" % (
            R, ci, c.get("source", "?"), c["start_step"], c["span"], c["active_words"]))
        res = solve_cascade(cfg, tag, timeout=timeout, o5_value=o5_value, budget=solve_budget)
        res["candidate"] = c
        attempts.append(res)
        opt = res.get("stage_optima", {})
        print("    -> status=%s found=%s O1..O5=%s O3(cond)=%s total=%.1fs" % (
            res["status"], res["found"],
            [opt.get(k) for k in ("o1", "o2", "o3", "o4", "o5")],
            res["min_conditions"], res["total_time"]))
        if not res["found"]:
            continue
        if not validate:
            chosen, chosen_out = res, res["out_file"]
            break
        # oracle: validate this candidate's DC(s) by finding a real SFS pair
        verified = None
        last_coll = None
        for dc_out in _sat_out_files(res, tag)[:max_validate]:
            coll = find_collision.solve_dc(R, dc_out, timeout=oracle_timeout)
            last_coll = coll
            print("       validate %s -> %s" % (os.path.basename(dc_out), coll.get("status")))
            if coll.get("verified"):
                verified = (dc_out, coll)
                break
            if coll.get("status") in ("timeout", "error"):
                break  # oracle gave up; don't burn more time on this candidate
        if best_effort is None and res["out_file"]:
            best_effort = (res, res["out_file"], last_coll)
        if verified:
            chosen_out, chosen_collision = verified
            chosen = res
            print("    => DC validated: verified SFS colliding pair found")
            break
        if last_coll and last_coll.get("status") == "invalid_dc":
            print("    => DC has no conforming pair (invalid_dc); trying next candidate")
        else:
            print("    => pair search did not complete in budget; trying next candidate")

    # fall back to a best-effort DC (found but pair unverified) so we always emit
    # a characteristic artifact, with the honest collision status attached
    if chosen is None and best_effort is not None:
        chosen, chosen_out, chosen_collision = best_effort

    # point the chosen record at the actually-validated trail so parse_dc and
    # standalone find_collision reference the same DC the pair was built from
    if chosen and chosen_out:
        chosen["out_file"] = chosen_out
    summary = {"R": R, "chosen": chosen, "chosen_out": chosen_out,
               "collision": chosen_collision, "attempts": attempts}
    out = os.path.join(RESULTS_DC, "dc_R%d.json" % R)
    with open(out, "w") as f:
        json.dump(summary, f, indent=2, default=str)
    if chosen and chosen_out:
        dc = read_differential_characteristic(BLOCK, chosen_out, R)
        with open(os.path.join(RESULTS_DC, "dc_R%d.txt" % R), "w") as f:
            for row in dc:
                if isinstance(row, list):
                    for line in row:
                        f.write(str(line) + "\n")
                else:
                    f.write(str(row) + "\n")
    if validate and chosen and chosen_collision:
        import find_collision
        find_collision._save(R, chosen["candidate"], chosen_collision)
    return summary


def run_round(R, lc_json=None, timeout=300, max_attempts=8, init_pro=97,
              validate=True, oracle_timeout=300, max_validate=1, solve_budget=None,
              o5_value=True):
    specs = build_specs(R, lc_json)
    return run_specs(R, specs, timeout=timeout, max_attempts=max_attempts,
                     init_pro=init_pro, validate=validate, oracle_timeout=oracle_timeout,
                     max_validate=max_validate, solve_budget=solve_budget, o5_value=o5_value)


if __name__ == "__main__":
    # usage: python3 dc_search.py R [per_call_timeout_s] [max_attempts] [o5_value 0|1]
    R = int(sys.argv[1])
    timeout = int(sys.argv[2]) if len(sys.argv) > 2 else 300
    max_attempts = int(sys.argv[3]) if len(sys.argv) > 3 else 8
    o5_value = bool(int(sys.argv[4])) if len(sys.argv) > 4 else True
    run_round(R, timeout=timeout, max_attempts=max_attempts, o5_value=o5_value)
